# Generated by Django 4.0.4 on 2022-04-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
