# Generated by Django 4.0.4 on 2022-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('desingr', 'desingr'), ('programmer', 'programmer')], max_length=30),
        ),
    ]
