# Generated by Django 4.0.4 on 2022-05-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_teams_alter_employee_name_alter_employee_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
    ]
