# Generated by Django 4.0.4 on 2022-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_employee_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teams',
            field=models.CharField(max_length=20),
        ),
    ]
