# Generated by Django 4.0.4 on 2022-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_employee_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teams',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
