# Generated by Django 4.0.4 on 2022-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_employee_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamDescription',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
